# -*- coding: utf-8 -*-
STATE_CAPITALS = {
    "AC": ("Rio Branco", "Acre"),
    "AL": ("Maceió", "Alagoas"),
    "AP": ("Macapá", "Amapá"),
    "AM": ("Manaus", "Amazonas"),
    "BA": ("Salvador", "Bahia"),
    "CE": ("Fortaleza", "Ceará"),
    "DF": ("Brasília", "Distrito Federal"),
    "ES": ("Vitória", "Espírito Santo"),
    "GO": ("Goiânia", "Goiás"),
    "MA": ("São Luís", "Maranhão"),
    "MT": ("Cuiabá", "Mato Grosso"),
    "MS": ("Campo Grande", "Mato Grosso do Sul"),
    "MG": ("Belo Horizonte", "Minas Gerais"),
    "PA": ("Belém", "Pará"),
    "PB": ("João Pessoa", "Paraíba"),
    "PR": ("Curitiba", "Paraná"),
    "PE": ("Recife", "Pernambuco"),
    "PI": ("Teresina", "Piauí"),
    "RJ": ("Rio de Janeiro", "Rio de Janeiro"),
    "RN": ("Natal", "Rio Grande do Norte"),
    "RS": ("Porto Alegre", "Rio Grande do Sul"),
    "RO": ("Porto Velho", "Rondônia"),
    "RR": ("Boa Vista", "Roraima"),
    "SC": ("Florianópolis", "Santa Catarina"),
    "SP": ("São Paulo", "São Paulo"),
    "SE": ("Aracaju", "Sergipe"),
    "TO": ("Palmas", "Tocantins"),
}
